"""empty message

Revision ID: 9fa9f15f1b82
Revises: a46ced88c447
Create Date: 2022-07-16 08:45:10.478640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa9f15f1b82'
down_revision = 'a46ced88c447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptocurrencies', sa.Column('logo', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cryptocurrencies', 'logo')
    # ### end Alembic commands ###
